name: GitHub Page

on:
  push:
    branches: development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.5'

      - name: Run
        run: |
          go get github.com/yuin/goldmark
          go run ./cmd/main.go

      - name: Commit
        run: |
           git config --global user.name "GitHub"
           git add ${GITHUB_WORKSPACE}/index.html
           git commit -m "Publish changes"
           git push -u origin ${GITHUB_REF}
